#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/caro/Programs/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/caro/Programs/nrn/i686/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/media/caro/Daten/Phd/DAP-Project/cell_fitting/model/channels/i686/.libs/libnrnmech.so" "$@"
